# Generated by Django 4.2.5 on 2023-09-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_moviename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviename',
            old_name='NameAr',
            new_name='nameAr',
        ),
        migrations.RenameField(
            model_name='moviename',
            old_name='NameFr',
            new_name='nameFr',
        ),
        migrations.RenameField(
            model_name='moviename',
            old_name='NameTr',
            new_name='nameTr',
        ),
    ]
