# Generated by Django 4.2.5 on 2023-09-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_namear_moviename_namear_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sektör Tanımı')),
                ('name_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sektör Tanımı (İngilizce)')),
            ],
        ),
    ]
